Crash_Preventer/Crash_Preventer.ino
Updated the code so that the if statement checks for the same distance but with a variable instead of getDistance, satisfies issue #17.
=> Updated if statement and added distance variable

webApplication/index.html
Main layout of the basic controls
relates #1
=> First draft of the web-application

carControl_v2.0/carControl_v2.0.ino
##Description:
Adds basic car controls that lets the car drive in any direction so that the user can control it
##Related issue:
Relates to #17 #1
Fixes #2
Co-Authored-By: fredriksjogren <fredriksjogren@users.noreply.github.com>
=> Adds basic car controls

webApplication/cameraFeed.py
We have now established a camera connection which is streaming on the webpage so that we can see the car's point of view.
Relates #10 #3
Co-Authored-By: nafenk <nafenk@users.noreply.github.com>
=> Camera feed in the web-application

carControl_v2.0/carControl_v2.0.ino
Some small comments changes to more accurately describe what the code does. 
Relates to #1
=> Further comments on carControl_v2.0

webApplication/index.html
the buttons now have shadows and show a pressing animation when clicked on, this is just a first draft for how we should make the buttons.
=> changed the design of the buttons

webApplication/cameraFeed.py
The camera feed is now working together with the web-application, the layout has been changed and a javascript code snippet is added as an example for us to keep working on.
Solves issues #10 #3
=> Update to the camera feed and web application

webApplication/index3.html
the layout for expanding the camera stream is set, and the expandable icon button is added but it is not still connected to the expandable screan feature so that has to be done.
#14
=>  the expandable screan feature is added

webApplication/index3.html
Updates to the fullScreen function. The expand button now enables the fullscreen, the proportions are adjusted to fit both on smartphones and laptop screen
closes #14
Co-authored-by: nafenk <gushajana@student.gu.se>
=> Updates to the fullScreen function

webApplication/index3.html
the camera stream works and can be accessed in a standard state and when it is expanded
co-authored-by: LinneaStigholt
=>  fixing the function of expanding camera feed

webApplication/index3.html
The code to send a post request when a button is pressed is now added, it is ready for testing with the python code
#1
=> Added javascript post request

carControl_v2.0/carControl_v2.0.ino
Changing the code to work better when facing an obstacle, so it can still be maneuvered
relates to #1
=> Fixing bug in arduino code

webApplication/index3.html
The fullscreen is now working and returns to the normal stream size when closed. The fullscreen button is now also on top of the stream for better readability. 
Relates to #14
=> Expandable Stream

webApplication/index3.html
the javascript code is fixed again and animation is added to the buttons(up to test)
=> update on the buttons

webApplication/index3.html
the color in the backgroup is blue, the color of the buttons is different and the expanding button doesn't have a backgroud.
#44
=>  UI update

webApplication/index3.html
It is a group of buttons which is intended to work as a slider. It is by default highlighting the "stop" step and is following as the user presses another speed "step"
#44
=> Added the first version of a speed controller

webApplication/index3.html
The javascript code regarding the post requests are now updated, just waiting for the new button design to be added
relating issues: #44
=> Javascript code modified

carControl_v3.0/controlSliderSketch.ino
Update with more switchcases to control the speed with a slider. Also improved the obstacle avoidance.
Co-authored by: @HannezHR @fredriksjogren and @JacobWalter 
Indirectly relates to #44
=> Changing the ardiuno code to work with a slider, to control the speed

carControl_v3.0/controlSliderSketch.ino
Removing snippets which are not being used anymore. Speed control is now fully functioning.
Fixes #11
=> Removing redundancy

webApplication/index3.html
We now only have 4 directions again and the design is changed to a more basic look which is adapted to different screens
related issues: #44
=> Updated the button design

RaspberryPi/InterfaceManual.txt
Short manual for enabling or disabling the interfaces on Raspberry Pi.
relates to #19
=> Manual for enabling/disabling interfaces

webApplication/connectorSlider.py
Merging the new updates from index3 into the connectorSlider-file
closes #44
=> Merging index3 and connector

webApplication/connectorSlider.py
The JavaScript-code sent the wrong commands, this fixes that.
=> Fixing small error
